---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: adicionando repositorio do java7
      apt_repository: repo=ppa:webupd8team/java state=present
    - name: Automatically select the Oracle License
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    - name: instalando o java7
      action: apt pkg={{item}} state=installed update-cache=yes force=yes
      with_items:
        - oracle-java7-set-default
        - libswt-gtk-3-java

    - name: baixando e extraindo android sdk para opt
      get_url: url=http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz dest=/tmp/android-sdk_r23.0.2-linux.tgz

    - unarchive: src=/tmp/android-sdk_r23.0.2-linux.tgz dest=/opt copy=no

    - name: dando permições para o grupo vagrant
      action: command chmod 777 -R  /opt/android-sdk-linux/

    - name: instalando o git, ant, nodejs e npm
      action: apt pkg={{item}} state=installed update-cache=yes force=yes
      with_items:
        - git
        - ant
        - nodejs
        - npm
    - name: criando link de nodejs para node
      command: sudo ln -s -f /usr/bin/nodejs /usr/bin/node

    - name: instalando o cordova
      command: sudo npm install -g cordova
    - name: instalando o ionic
      command: sudo npm install -g ionic

    - name: adicionando necessidades para o build
      action: apt pkg={{item}} state=installed update-cache=yes force=yes
      with_items:
        - lib32z1
        - lib32stdc++6
