---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: adicionando repositorio do java7
      apt_repository: repo=ppa:webupd8team/java state=present
    - name: Automatically select the Oracle License
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    - name: instalando o java7
      action: apt pkg={{item}} state=installed update-cache=yes force=yes
      with_items:
        - oracle-java7-set-default
        - libswt-gtk-3-java

    - name: adicionando repositorio do android-studio
      apt_repository: repo=ppa:paolorotolo/android-studio  state=present
    - name: instalando o android-studio
      apt: pkg=android-studio state=installed update-cache=yes force=yes

    - name: instalando o git
      apt: pkg=git state=installed update_cache=true
    - name: instalando o ant
      apt: pkg=ant state=installed update_cache=true

    - name: instalando o node.js
      apt: pkg=nodejs state=installed update_cache=true
    - name: instalando o npm
      apt: pkg=npm state=installed update_cache=true
    - name: criando link de nodejs para node
      command: sudo ln -s -f /usr/bin/nodejs /usr/bin/node

    - name: instalando o cordova
      command: sudo npm install -g cordova
    - name: instalando o ionic
      command: sudo npm install -g ionic

    - name: adicionando necessidades para o build
      action: apt pkg={{item}} state=installed update-cache=yes force=yes
      with_items:
        - lib32z1
        - lib32stdc++6

    - name: adicionando necessidades para a emulação
      apt: pkg=libgl1-mesa-dev state=installed update_cache=true
