---
- hosts: all
  user: vagrant
  sudo: yes
  roles:
        - ansible-java8-oracle
        - ansible-role-android-sdk
        - ansible-nodejs-role
        - ansible-role-ionic
  tasks:
    - name: install adb and fastboot
      apt: pkg={{item}} state=installed
      with_items:
        - android-tools-adb
        - android-tools-fastboot

- hosts: all
  user: vagrant
  gather_facts: no
  tasks:
    - name: set bashrc
      shell: cat /vagrant/bashrc >> /home/vagrant/.bashrc
